
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
/// <summary>
/// 动作打断力与抗打断韧性
/// </summary>
public sealed partial class ActionResilience : Luban.BeanBase
{
    public ActionResilience(JSONNode _buf) 
    {
        { if(!_buf["interrupt_level"].IsNumber) { throw new SerializationException(); }  InterruptLevel = _buf["interrupt_level"]; }
        { if(!_buf["resilience_bonus"].IsNumber) { throw new SerializationException(); }  ResilienceBonus = _buf["resilience_bonus"]; }
    }

    public static ActionResilience DeserializeActionResilience(JSONNode _buf)
    {
        return new ZZZ.ActionResilience(_buf);
    }

    /// <summary>
    /// 动作附带打断等级（0=不可打断，1=常规轻击，5=招架弹刀，10=强力爆发，999=绝对打断）
    /// </summary>
    public readonly int InterruptLevel;
    /// <summary>
    /// 动作持续期间获得的额外抗打断韧性加成（0=常规轻攻击，50=霸体/重攻击）
    /// </summary>
    public readonly int ResilienceBonus;
   
    public const int __ID__ = -1301992421;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "interruptLevel:" + InterruptLevel + ","
        + "resilienceBonus:" + ResilienceBonus + ","
        + "}";
    }
}
}

