
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// Buff 效果类型
    /// </summary>
    public enum BuffEffectType
    {
        /// <summary>
        /// 属性修改（增减攻防、暴击、抗打断）
        /// </summary>
        ModifyAttribute = 0,
        /// <summary>
        /// 极限闪避（子弹时间、阻断受击）
        /// </summary>
        PerfectEvade = 10,
        /// <summary>
        /// 纯无敌（无害免疫）
        /// </summary>
        Invincible = 20,
        /// <summary>
        /// 持续伤害 DoT (灼烧/中毒/感电)
        /// </summary>
        DamageOverTime = 30,
        /// <summary>
        /// 持续治疗 HoT
        /// </summary>
        HealOverTime = 40,
        /// <summary>
        /// 控制类 (冻结/眩晕/束缚/减速)
        /// </summary>
        CrowdControl = 50,
        /// <summary>
        /// 护盾类 (吸收特定数值伤害)
        /// </summary>
        Shield = 60,
        /// <summary>
        /// 事件触发类 (命中/受击/击杀/闪避后触发衍生效果)
        /// </summary>
        EventTrigger = 70,
    }

} 

