
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// Buff 触发事件时机
    /// </summary>
    public enum BuffTriggerEvent
    {
        None = 0,
        /// <summary>
        /// 攻击命中敌人时
        /// </summary>
        OnHit = 10,
        /// <summary>
        /// 受到敌人攻击时
        /// </summary>
        OnBeHit = 20,
        /// <summary>
        /// 成功触发极限闪避时
        /// </summary>
        OnPerfectEvade = 30,
        /// <summary>
        /// 击杀敌人时
        /// </summary>
        OnKill = 40,
        /// <summary>
        /// 护盾破裂时
        /// </summary>
        OnShieldBroken = 50,
    }

} 

