
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// Buff 叠加与刷新策略
    /// </summary>
    public enum BuffStackBehavior
    {
        /// <summary>
        /// 叠加层数，并刷新剩余持续时间
        /// </summary>
        RefreshDuration = 0,
        /// <summary>
        /// 叠加层数，不刷新持续时间
        /// </summary>
        NoRefresh = 10,
        /// <summary>
        /// 达到上限时拒绝新施加
        /// </summary>
        Reject = 20,
        /// <summary>
        /// 移除旧实例，全新施加
        /// </summary>
        Replace = 30,
        /// <summary>
        /// 独立多实例共存（每层独立计时）
        /// </summary>
        Independent = 40,
    }

} 

