
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
/// <summary>
/// Buff数据基类
/// </summary>
public sealed partial class BuffEffectData : Luban.BeanBase
{
    public BuffEffectData(JSONNode _buf) 
    {
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = (ZZZ.BuffEffectType)_buf["effect_type"].AsInt; }
        { if(!_buf["trigger_event"].IsNumber) { throw new SerializationException(); }  TriggerEvent = (ZZZ.BuffTriggerEvent)_buf["trigger_event"].AsInt; }
        { if(!_buf["attr_id"].IsNumber) { throw new SerializationException(); }  AttrId = (ZZZ.AttributeId)_buf["attr_id"].AsInt; }
        { if(!_buf["param_int1"].IsNumber) { throw new SerializationException(); }  ParamInt1 = _buf["param_int1"]; }
        { if(!_buf["param_float1"].IsNumber) { throw new SerializationException(); }  ParamFloat1 = _buf["param_float1"]; }
        { if(!_buf["param_float2"].IsNumber) { throw new SerializationException(); }  ParamFloat2 = _buf["param_float2"]; }
        { if(!_buf["param_bool1"].IsBoolean) { throw new SerializationException(); }  ParamBool1 = _buf["param_bool1"]; }
        { if(!_buf["param_str1"].IsString) { throw new SerializationException(); }  ParamStr1 = _buf["param_str1"]; }
    }

    public static BuffEffectData DeserializeBuffEffectData(JSONNode _buf)
    {
        return new ZZZ.BuffEffectData(_buf);
    }

    /// <summary>
    /// 效果类型枚举,路由创建具体的逻辑执行器
    /// </summary>
    public readonly ZZZ.BuffEffectType EffectType;
    /// <summary>
    /// 事件监听时机,声明何时触发（常驻效果填 None）
    /// </summary>
    public readonly ZZZ.BuffTriggerEvent TriggerEvent;
    /// <summary>
    /// 作用属性 ID,属性加成时使用（如 ATK, BaseResilience）
    /// </summary>
    public readonly ZZZ.AttributeId AttrId;
    /// <summary>
    /// 整型参数 1,属性修改运算类型（0=Flat, 1=Percent）/ 优先级
    /// </summary>
    public readonly int ParamInt1;
    /// <summary>
    /// 浮点参数 1,数值大小（如增伤 0.2）/ 子弹时间流速 (0.1)
    /// </summary>
    public readonly float ParamFloat1;
    /// <summary>
    /// 浮点参数 2,跳字间隔（DoT 间隔 0.5s）/ 子弹时间持续 (0.8s)
    /// </summary>
    public readonly float ParamFloat2;
    /// <summary>
    /// 布尔参数 1,是否随层数倍增 / 是否平滑缓出恢复
    /// </summary>
    public readonly bool ParamBool1;
    /// <summary>
    /// 字符串参数 1,视效音效寻址 Key / 关联触发的子 BuffID / 标签
    /// </summary>
    public readonly string ParamStr1;
   
    public const int __ID__ = 1740471554;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "effectType:" + EffectType + ","
        + "triggerEvent:" + TriggerEvent + ","
        + "attrId:" + AttrId + ","
        + "paramInt1:" + ParamInt1 + ","
        + "paramFloat1:" + ParamFloat1 + ","
        + "paramFloat2:" + ParamFloat2 + ","
        + "paramBool1:" + ParamBool1 + ","
        + "paramStr1:" + ParamStr1 + ","
        + "}";
    }
}
}

