
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Tags.Add(__v0); }   }
        { if(!_buf["lifetime_type"].IsNumber) { throw new SerializationException(); }  LifetimeType = (ZZZ.BuffLifetimeType)_buf["lifetime_type"].AsInt; }
        { if(!_buf["base_duration"].IsNumber) { throw new SerializationException(); }  BaseDuration = _buf["base_duration"]; }
        { if(!_buf["max_stack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["max_stack"]; }
        { if(!_buf["stack_behavior"].IsNumber) { throw new SerializationException(); }  StackBehavior = (ZZZ.BuffStackBehavior)_buf["stack_behavior"].AsInt; }
        { if(!_buf["charge_count"].IsNumber) { throw new SerializationException(); }  ChargeCount = _buf["charge_count"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<ZZZ.BuffEffectData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ZZZ.BuffEffectData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.ZZZ.BuffEffectData.DeserializeBuffEffectData(__e0);  }  Effects.Add(__v0); }   }
    }

    public static Buff DeserializeBuff(JSONNode _buf)
    {
        return new ZZZ.Buff(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// 生命周期类型
    /// </summary>
    public readonly ZZZ.BuffLifetimeType LifetimeType;
    /// <summary>
    /// 基础持续时间
    /// </summary>
    public readonly float BaseDuration;
    /// <summary>
    /// 最大堆叠数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 堆叠策略
    /// </summary>
    public readonly ZZZ.BuffStackBehavior StackBehavior;
    /// <summary>
    /// 可充能数
    /// </summary>
    public readonly int ChargeCount;
    /// <summary>
    /// 执行效果
    /// </summary>
    public readonly System.Collections.Generic.List<ZZZ.BuffEffectData> Effects;
   
    public const int __ID__ = -1168719673;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "lifetimeType:" + LifetimeType + ","
        + "baseDuration:" + BaseDuration + ","
        + "maxStack:" + MaxStack + ","
        + "stackBehavior:" + StackBehavior + ","
        + "chargeCount:" + ChargeCount + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

