
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
public sealed partial class CharacterElement : Luban.BeanBase
{
    public CharacterElement(JSONNode _buf) 
    {
        { if(!_buf["characterId"].IsNumber) { throw new SerializationException(); }  CharacterId = (ZZZ.CharacterId)_buf["characterId"].AsInt; }
    }

    public static CharacterElement DeserializeCharacterElement(JSONNode _buf)
    {
        return new ZZZ.CharacterElement(_buf);
    }

    /// <summary>
    /// 角色id
    /// </summary>
    public readonly ZZZ.CharacterId CharacterId;
   
    public const int __ID__ = -1648939513;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "characterId:" + CharacterId + ","
        + "}";
    }
}
}

