
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// 角色ID
    /// </summary>
    public enum CharacterId
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 安比
        /// </summary>
        Anbi = 1001,
        /// <summary>
        /// 星见雅
        /// </summary>
        Miyabi = 1002,
        /// <summary>
        /// 艾莲
        /// </summary>
        Ellen = 1003,
    }

} 

