
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// 消耗计算类型
    /// </summary>
    public enum CostType
    {
        /// <summary>
        /// 固定数值扣减
        /// </summary>
        FixedValue = 0,
        /// <summary>
        /// 最大值百分比扣减
        /// </summary>
        PercentMax = 1,
        /// <summary>
        /// 当前值百分比扣减
        /// </summary>
        PercentCurrent = 2,
    }

} 

