
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ZZZ
{ 
    /// <summary>
    /// 命中策略
    /// </summary>
    public enum EffectTriggerPolicy
    {
        /// <summary>
        /// 每次命中触发
        /// </summary>
        EveryHit = 1,
        /// <summary>
        /// 仅首次命中触发
        /// </summary>
        FirstHitOnly = 2,
    }

} 

