
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
public sealed partial class HitEffect : Luban.BeanBase
{
    public HitEffect(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<ZZZ.HitEffectData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ZZZ.HitEffectData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.ZZZ.HitEffectData.DeserializeHitEffectData(__e0);  }  Effects.Add(__v0); }   }
    }

    public static HitEffect DeserializeHitEffect(JSONNode _buf)
    {
        return new ZZZ.HitEffect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 命中效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<ZZZ.HitEffectData> Effects;
   
    public const int __ID__ = -1902725360;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

