
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
/// <summary>
/// 角色元素与抗性表
/// </summary>
public partial class TbCharacterElement
{
    private readonly System.Collections.Generic.Dictionary<ZZZ.CharacterId, ZZZ.CharacterElement> _dataMap;
    private readonly System.Collections.Generic.List<ZZZ.CharacterElement> _dataList;
    
    public TbCharacterElement(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<ZZZ.CharacterId, ZZZ.CharacterElement>(count);
        _dataList = new System.Collections.Generic.List<ZZZ.CharacterElement>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ZZZ.CharacterElement _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ZZZ.CharacterElement.DeserializeCharacterElement(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ZZZ.CharacterId, ZZZ.CharacterElement> DataMap => _dataMap;
    public System.Collections.Generic.List<ZZZ.CharacterElement> DataList => _dataList;

    public ZZZ.CharacterElement GetOrDefault(ZZZ.CharacterId key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ZZZ.CharacterElement Get(ZZZ.CharacterId key) => _dataMap[key];
    public ZZZ.CharacterElement this[ZZZ.CharacterId key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

