
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ZZZ
{
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, ZZZ.Skill> _dataMap;
    private readonly System.Collections.Generic.List<ZZZ.Skill> _dataList;
    
    public TbSkill(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, ZZZ.Skill>(count);
        _dataList = new System.Collections.Generic.List<ZZZ.Skill>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ZZZ.Skill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ZZZ.Skill.DeserializeSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ZZZ.Skill> DataMap => _dataMap;
    public System.Collections.Generic.List<ZZZ.Skill> DataList => _dataList;

    public ZZZ.Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ZZZ.Skill Get(int key) => _dataMap[key];
    public ZZZ.Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

